server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8123
          predicates:
            - Path=/**
  redis:
    host: localhost
    port: 6379
    database: 1

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: star-api-admin-provider
  protocol:
    name: dubbo
    port: 22223
  registry:
    id: nacos-registry
    # todo 上线需要换成内网地址
    address: nacos://localhost:8848

